[package]
name = "bns-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = { workspace = true }
uuid = { version = "1.16.0", features = ["v4"] }
tokio = { workspace = true }
base64 = "0.22.1"
