name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Just
      run: |
        sudo apt-get update
        sudo apt-get install -y just
    #   run: just linux-x86
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: ./README.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
