name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Just
      run: |
        sudo apt-get update
        sudo apt-get install -y just
    - name: Build
      run: just linux-x86
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        files: ./payload/client-x86_64-unknown-linux-gnu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
